import fs from 'fs';

const path = 'src/context/LanguageContext.tsx';
let content = fs.readFileSync(path, 'utf-8');

const newTranslationsEn = `
    'landing.hero.title1': 'The toolkit for',
    'landing.hero.accent': 'E-commerce',
    'landing.hero.title2': 'growth',
    'landing.hero.desc': 'The all-in-one AI that helps businesses manage their marketing perfectly to make more sales and attract new customers easily.',
    'landing.hero.cta.primary': 'Access AI',
    'landing.hero.cta.secondary': 'View Plans',
    'landing.features.title': 'Everything you need to scale',
    'landing.features.subtitle': 'A complete suite of tools designed to streamline your operations.',
    'landing.features.ai.title': 'AI Content Generation',
    'landing.features.ai.desc': 'Generate high-converting emails, SMS, scripts, and ad copy in seconds using advanced AI models.',
    'landing.features.calc.title': 'Profit Analytics',
    'landing.features.calc.desc': 'Calculate margins, ROAS break-even, ROI, and customer lifetime value with precision.',
    'landing.features.lang.title': 'Multi-language',
    'landing.features.lang.desc': 'Translate your generated marketing content into 12+ languages instantly with one click.',
    'landing.showcase.title': 'Powerful tools, zero complexity',
    'landing.showcase.subtitle': 'From content creation to financial analysis. High performance marketing and operations in one tab.',
    'landing.showcase.ai.title': 'AI Content Tools',
    'landing.showcase.ai.badge': 'Hyper-converting marketing copies',
    'landing.showcase.ai.desc': 'Instantly craft personalized copy adapted to your brand identity, target demographic, and promotional hooks.',
    'landing.showcase.ai.tool1': 'Email Generator',
    'landing.showcase.ai.tool1Desc': 'High-converting email campaigns & sequences',
    'landing.showcase.ai.tool2': 'SMS Generator',
    'landing.showcase.ai.tool2Desc': 'Punchy SMS marketing messages with viral velocity',
    'landing.showcase.ai.tool3': 'Script Writer',
    'landing.showcase.ai.tool3Desc': 'Sales scripts and persuasive presentation pitches',
    'landing.showcase.ops.title': 'Ops & Strategy',
    'landing.showcase.ops.badge': 'Co-pilot for store decisions',
    'landing.showcase.ops.desc': 'Consult with world-class growth advisors. Formulate pricing schemes, product lines, and marketing vectors.',
    'landing.showcase.ops.tool1': 'Strategy Chat',
    'landing.showcase.ops.tool1Desc': 'Multi-model conversational assistant loaded with business contextual workflows',
    'landing.showcase.ops.keyTip': 'Connect OpenAI, Claude or Gemini keys directly inside',
    'landing.showcase.ops.cta': 'Launch Strategy Chat',
    'landing.showcase.calc.title': 'Calculators',
    'landing.showcase.calc.badge': 'Venture-grade financial audits',
    'landing.showcase.calc.desc': 'Model acquisition spends, customer retention lifetime values, and pricing models safely with high precision calculators.',
    'landing.showcase.calc.tool1': 'Profit Margin',
    'landing.showcase.calc.tool1Desc': 'Analyze item COGS and net margin ratios with precision',
    'landing.showcase.calc.tool2': 'ROAS Calculator',
    'landing.showcase.calc.tool2Desc': 'Define break-even ratio for advertising campaign scales',
    'landing.showcase.calc.tool3': 'ROI Calculator',
    'landing.showcase.calc.tool3Desc': 'Track return metrics across customized ad buys and setups',
    'common.alsoIncludes': 'Also Includes',
    'landing.comparison.title': 'Why operators choose EcomBoost',
    'landing.comparison.subtitle': 'Compare our active intelligence against standard methods.',
    'landing.comparison.capability': 'Capability',
    'landing.comparison.standardAgency': 'Standard Agency',
    'landing.comparison.row1.f': 'Turnaround Time', 'landing.comparison.row1.a': 'Seconds (Instant)', 'landing.comparison.row1.s': '3-14 Days',
    'landing.comparison.row2.f': 'Total Cost / Output', 'landing.comparison.row2.a': 'Included in Sub', 'landing.comparison.row2.s': '$2,500+ / mo',
    'landing.comparison.row3.f': 'Time Saved per Week', 'landing.comparison.row3.a': '72% Reduction', 'landing.comparison.row3.s': '0% (Manual)',
    'landing.comparison.row4.f': 'Money Gen per Client', 'landing.comparison.row4.a': '+350% Growth', 'landing.comparison.row4.s': 'Baseline',
    'landing.comparison.row5.f': 'Ops Cost Saved', 'landing.comparison.row5.a': '90% Less', 'landing.comparison.row5.s': 'Standard',
    'landing.comparison.row6.f': 'Language Scale', 'landing.comparison.row6.a': '12+ Instantly', 'landing.comparison.row6.s': 'Manual/Human',
    'landing.comparison.row7.f': 'Operations Scale', 'landing.comparison.row7.a': 'Unlimited Clients', 'landing.comparison.row7.s': 'Limited by Staff',
    'landing.reviews.user1.role': 'SaaS Creator & Founder',
    'landing.reviews.user1.comment': 'Honestly, after finishing our SaaS development, marketing was our biggest bottleneck. We needed logo styling, sponsor decks, and high-converting ads but were too lazy to hire slow agencies. EcomBoost did everything for us instantly! It gave our application a real marketing boost with absolutely zero extra spending outside our subscription. Essential for builders.',
    'landing.reviews.user2.role': 'Product Founder',
    'landing.reviews.user2.comment': 'Sponsoring and setting up enterprise-grade marketing campaigns can cost thousands of dollars. EcomBoost literally handles it all in one dashboard. From viral ad scripts to high-precision profit margins, we launched our brand identity overnight without spending any extra cash of our budget. Magnificent.',
    'landing.reviews.user3.role': 'Growth Specialist',
    'landing.reviews.user3.comment': 'Many brands finish their tools and then struggle to create punchy ads and sequences. EcomBoost is the ultimate lazy marketer\\'s dream. It builds your whole brand marketing stack automatically. No expensive copywriters or agencies needed—just select an AI tool, pick your campaign strategy, and enjoy a massive boost in conversions!',
    'landing.faq.title': 'FAQ',
    'landing.faq.subtitle': 'Frequently Asked Questions about EcomBoost.org',
    'landing.faq.q1.q': 'What is EcomBoost.org exactly?',
    'landing.faq.q1.a': 'EcomBoost.org is a specialized suite of tools for e-commerce owners. It combines venture-grade financial calculators, AI-powered content generation (for ads, emails, and SMS), and deep competitive research capabilities to help you scale your store profitably.',
    'landing.faq.q2.q': 'Do I need my own OpenAI / Claude API keys?',
    'landing.faq.q2.a': 'No. Our Pro and Business tiers give you unlimited native access to top models. However, we also provide a "Bring Your Own Key" mode if you want completely private and unlimited usage through your own developer accounts.',
    'landing.faq.q3.q': 'Can it translate my generated emails and ads?',
    'landing.faq.q3.a': 'Yes, our platform supports instant multi-language translation. Any script, email, or hook you generate can be globally translated instantly, allowing you to easily duplicate successful campaigns across international markets.',
    'landing.faq.q4.q': 'Is the data saved securely?',
    'landing.faq.q4.a': 'Yes. Client-side logic, offline capabilities, and secure cloud sync ensure your ad formulations and strategies are kept totally private. We do not use your private financial calculator inputs to train our AI models.',
    'landing.faq.q5.q': 'How do the built-in financial calculators ensure precision in my ad accounts and product margin calculations?',
    'landing.faq.q5.a': 'All calculators in EcomBoost.org are designed from standard venture-grade e-commerce accounting frameworks. We do not use simplified, rough estimation formulas. For example, our ROAS Calculator maps the absolute break-even ratio by factoring in cost-of-goods-sold (COGS), average order value (AOV), transaction gateway fees, and operating overheads. Our Customer LTV calculator uses multi-cohort analysis (order frequency, average retention span, churn rate) to show exactly how much you can afford for customer acquisition cost (CAC). Everything is represented in real-time, high-contrast visual charts to give you instant mathematical clarity before scaling.',
`;

const newTranslationsFr = `
    'landing.hero.title1': 'La boîte à outils pour',
    'landing.hero.accent': 'le E-commerce',
    'landing.hero.title2': 'et la croissance',
    'landing.hero.desc': 'L\\'IA tout-en-un qui aide les entreprises à gérer parfaitement leur marketing pour faire plus de ventes et attirer de nouveaux clients facilement.',
    'landing.hero.cta.primary': 'Accéder à l\\'IA',
    'landing.hero.cta.secondary': 'Voir les offres',
    'landing.features.title': 'Tout pour passer à l\\'échelle',
    'landing.features.subtitle': 'Une suite complète de création conçue pour rationaliser vos opérations.',
    'landing.features.ai.title': 'Génération IA de contenu',
    'landing.features.ai.desc': 'Générez des emails, des SMS, des scripts et des textes publicitaires à fort taux de conversion en quelques secondes.',
    'landing.features.calc.title': 'Analytiques P&L',
    'landing.features.calc.desc': 'Calculez les marges, le seuil de rentabilité ROAS, le ROI et la valeur à vie du client avec une précision professionnelle.',
    'landing.features.lang.title': 'Multi-langues',
    'landing.features.lang.desc': 'Traduisez instantanément votre contenu marketing généré dans plus de 12 langues.',
    'landing.showcase.title': 'Outils puissants, zéro complexité',
    'landing.showcase.subtitle': 'De la création de contenu à l\\'analyse financière. Marketing et opérations haute performance dans un seul onglet.',
    'landing.showcase.ai.title': 'Outils de contenu IA',
    'landing.showcase.ai.badge': 'Textes marketing hyper-convertissants',
    'landing.showcase.ai.desc': 'Créez instantanément des textes personnalisés adaptés à votre identité de marque, votre démographie cible et vos accroches promotionnelles.',
    'landing.showcase.ai.tool1': 'Générateur d\\'emails',
    'landing.showcase.ai.tool1Desc': 'Campagnes et séquences d\\'emails à fort taux de conversion',
    'landing.showcase.ai.tool2': 'Générateur de SMS',
    'landing.showcase.ai.tool2Desc': 'Messages marketing SMS percutants à vitesse virale',
    'landing.showcase.ai.tool3': 'Rédacteur de script',
    'landing.showcase.ai.tool3Desc': 'Scripts de vente et présentations persuasives',
    'landing.showcase.ops.title': 'Ops & Stratégie',
    'landing.showcase.ops.badge': 'Co-pilote décisionnel',
    'landing.showcase.ops.desc': 'Consultez des conseillers en croissance de classe mondiale. Formulez des stratégies de prix, des lignes de produits et des vecteurs de marketing.',
    'landing.showcase.ops.tool1': 'Chat Stratégique',
    'landing.showcase.ops.tool1Desc': 'Assistant conversationnel avec flux de travail contextuels professionnels',
    'landing.showcase.ops.keyTip': 'Connectez vos clés API directement',
    'landing.showcase.ops.cta': 'Lancer le Chat',
    'landing.showcase.calc.title': 'Calculateurs',
    'landing.showcase.calc.badge': 'Audits financiers rigoureux',
    'landing.showcase.calc.desc': 'Modélisez les dépenses d\\'acquisition, les valeurs à vie des clients et les prix en toute sécurité avec des calculatrices de haute précision.',
    'landing.showcase.calc.tool1': 'Marge bénéficiaire',
    'landing.showcase.calc.tool1Desc': 'Analysez le coût de revient (COGS) et la marge nette.',
    'landing.showcase.calc.tool2': 'Calculateur ROAS',
    'landing.showcase.calc.tool2Desc': 'Définissez le seuil de rentabilité pour vos campagnes publicitaires.',
    'landing.showcase.calc.tool3': 'Calculateur ROI',
    'landing.showcase.calc.tool3Desc': 'Suivez les retours sur investissement pour vos configurations d\\'achat de publicités.',
    'common.alsoIncludes': 'Comprend aussi',
    'landing.comparison.title': 'Pourquoi les professionnels choisissent EcomBoost',
    'landing.comparison.subtitle': 'Comparez notre intelligence active par rapport aux méthodes standards.',
    'landing.comparison.capability': 'Capacité',
    'landing.comparison.standardAgency': 'Agence Standard',
    'landing.comparison.row1.f': 'Temps de réponse', 'landing.comparison.row1.a': 'Secondes (Immédiat)', 'landing.comparison.row1.s': '1 à 2 Semaines',
    'landing.comparison.row2.f': 'Coût Total / Rendement', 'landing.comparison.row2.a': 'Compris', 'landing.comparison.row2.s': '2500$+ / mois',
    'landing.comparison.row3.f': 'Temps gagné par semaine', 'landing.comparison.row3.a': '-72%', 'landing.comparison.row3.s': '0% (Manuel)',
    'landing.comparison.row4.f': 'Croissance Rénum.', 'landing.comparison.row4.a': '+350% Croissance', 'landing.comparison.row4.s': 'Basique',
    'landing.comparison.row5.f': 'Coût des Opérations', 'landing.comparison.row5.a': '-90%', 'landing.comparison.row5.s': 'Normal',
    'landing.comparison.row6.f': 'Adaptabilité linguistique', 'landing.comparison.row6.a': '12+ Instantanément', 'landing.comparison.row6.s': 'Manuel',
    'landing.comparison.row7.f': 'Croissance Client', 'landing.comparison.row7.a': 'Sans Limite', 'landing.comparison.row7.s': 'Main d\\'oeuvre',
    'landing.reviews.user1.role': 'Créateur SaaS',
    'landing.reviews.user1.comment': 'Honnêtement, après avoir terminé le développement, le marketing était un goulot d\\'étranglement. Il nous fallait des textes rapidement sans embaucher des agences chères. EcomBoost a tout fait pour nous! Un boost total pour zero dépense supplémentaire.',
    'landing.reviews.user2.role': 'CEO Produit',
    'landing.reviews.user2.comment': 'Financer des campagnes robustes coûte incroyablement cher. EcomBoost gère l\\'entier de nos textes, vidéos hooks, et calcul de marges précisément. Vraiment magnifique pour lancer rapidement sa marque.',
    'landing.reviews.user3.role': 'Expert Croissance',
    'landing.reviews.user3.comment': 'Les vendeurs dépensent beaucoup pour leurs outils et échouent sur les textes de vente. L\\'IA EcomBoost est incroyable, c\\'est le rêve de chaque marketeur. Aucun rédacteur onéreux nécessaire! Vous lancez le chat IA et vous convertissez. Impressionnant.',
    'landing.faq.title': 'FAQ',
    'landing.faq.subtitle': 'Questions posées fréquemment',
    'landing.faq.q1.q': 'Qu\\'est-ce que EcomBoost.org exactement?',
    'landing.faq.q1.a': 'EcomBoost.org est une suite spécialisée d\\'outils pour les propriétaires e-commerce. Elle combine des calculatrices financières pointues, de la génération de contenu pilotée par IA et une recherche concurrentielle avancée pour maximiser vos bénéfices.',
    'landing.faq.q2.q': 'Ai-je besoin de mes propres clés API OpenAI/Claude ?',
    'landing.faq.q2.a': 'Non. Nos offres Pro et Business offrent un accès natif aux modèles de pointe. Toutefois, vous pouvez connecter vos propres clés (BYOK) pour une flexibilité totale via votre compte développeur privé.',
    'landing.faq.q3.q': 'L\\'outil peut-il traduire le texte immédiatement ?',
    'landing.faq.q3.a': 'Oui, tous nos textes (scripts, emails, etc.) incluent un support multilingue. Un seul clic et il est prêt pour le monde.',
    'landing.faq.q4.q': 'Est-ce que mes calculs restent confidentiels ?',
    'landing.faq.q4.a': 'Totalement. La plupart de nos outils utilisent des fonctions clients-side sans stocker de données de confidentialité liées à vos revenus. Aucune de ces données n\\'est utilisée à des fins de formation IA.',
    'landing.faq.q5.q': 'À quel point les calculatrices de marge et ROAS sont-elles précises ?',
    'landing.faq.q5.a': 'Toutes les calculatrices sont certifiées avec les mêmes formules utilisées par les professionnels du marché. Par exemple, le compte de Lifetime Value client (LTV) utilise l\\'analyse en multi-cohorte pour ajuster son ratio à vos performances opérationnelles sans erreurs.',
`;

content = content.replace(/(en:\s*\{)/, "$1\n" + newTranslationsEn);
content = content.replace(/(fr:\s*\{)/, "$1\n" + newTranslationsFr);
content = content.replace(/(es:\s*\{)/, "$1\n" + newTranslationsEn);
content = content.replace(/(de:\s*\{)/, "$1\n" + newTranslationsEn);
content = content.replace(/(it:\s*\{)/, "$1\n" + newTranslationsEn);
content = content.replace(/(ru:\s*\{)/, "$1\n" + newTranslationsEn);

fs.writeFileSync(path, content, 'utf-8');
console.log('Language files updated');
