import fs from 'fs';

const blueprint = JSON.parse(fs.readFileSync('firebase-blueprint.json', 'utf8'));

blueprint.entities.AdminSettings = {
  title: "AdminSettings",
  description: "Global admin settings like maintenance mode",
  type: "object",
  properties: {
    maintenanceMode: { type: "boolean" },
    maintenanceMessage: { type: "string" }
  },
  required: ["maintenanceMode"]
};

blueprint.entities.AffiliateLink = {
  title: "AffiliateLink",
  description: "Affiliate links generated by users",
  type: "object",
  properties: {
    userId: { type: "string" },
    shortCode: { type: "string" },
    createdAt: { type: "number" }
  },
  required: ["userId", "shortCode", "createdAt"]
};

blueprint.entities.AffiliateClick = {
  title: "AffiliateClick",
  description: "Clicks on affiliate links",
  type: "object",
  properties: {
    linkId: { type: "string" }, // Maps to AffiliateLink document ID
    ip: { type: "string" },
    userAgent: { type: "string" },
    clickedAt: { type: "number" }
  },
  required: ["linkId", "clickedAt", "ip", "userAgent"]
};

// Update UserProfile
blueprint.entities.UserProfile.properties.isBanned = { type: "boolean" };
blueprint.entities.UserProfile.properties.createdAt = { type: "number" };
blueprint.entities.UserProfile.properties.userAgent = { type: "string" };
blueprint.entities.UserProfile.properties.referredByLink = { type: "string" };

blueprint.firestore["/admin/settings"] = {
  schema: "AdminSettings",
  description: "Global settings"
};

blueprint.firestore["/affiliateLinks/{linkId}"] = {
  schema: "AffiliateLink",
  description: "User affiliate links"
};

blueprint.firestore["/affiliateClicks/{clickId}"] = {
  schema: "AffiliateClick",
  description: "Clicks on affiliate links"
};

fs.writeFileSync('firebase-blueprint.json', JSON.stringify(blueprint, null, 2));
